### ISSUE TITLE
Doesn't sort numeric fields

### ISSUE THREAD

**Issue by rossburton** [tumblr/data-lasso#7]
If you have a data set with numeric values in, the values don't get sorted as you'd expect: they're sorted as strings (1 < 12 < 9).

For CSV data this is sort-of understandable as you have no way of telling, but for JSON can't you introspect the data type?

**Comment by tgilan** [comment]
Yes, that is something that I noticed too and is on my roadmap to fix.

Originally there was some distinction made between numerical fields and categorical fields (strings), but that affected performance poorly and was mostly hardcoded to certain field names. However there is more intelligent approach I can take here - every column can be initially considered numerical, until content of the field proves otherwise.

**Comment by tgilan** [comment]
The sorting of numeric values is now what you would expect - 1 <  9 < 12. It was fixed in this [PR](https://github.com/tumblr/data-lasso/pull/8)

**Comment by rossburton** [comment]
On 4 December 2015 at 20:34, Tim G <notifications@github.com> wrote:

> The sorting of numeric values is now what you would expect - 1 < 9 < 12.
> It was fixed in this PR <https://github.com/tumblr/data-lasso/pull/8>
>
>
Presumably the demo instance online wasn't updated?  If it was, then it
isn't working.

Ross

**Comment by tgilan** [comment]
Good catch, updated the demo with latest build files. Thanks!
